### ISSUE TITLE
Please clarify any usage restrictions of software deliverables

### ISSUE THREAD

**Issue by kenrussell** [gpuweb/admin#11]
In #8, the CG charter ( https://gpuweb.github.io/admin/cg-charter.html ) was updated to avoid being overly restrictive, and the development of an ANGLE-like library was added as a possibility to the section "Test Suites and Other Software".

I am not a lawyer and do not know the consequences of the W3C Software and Document License ( https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document ) as it relates to the "Out of Scope" section.

Could you please add a follow-on paragraph or couple of sentences to the "Test Suites and Other Software" section clarifying any implicit or explicit restrictions on usage of this library?

Thank you.

**Comment by othermaciej** [comment]
The charter doesn't impose any restrictions beyond the W3C Software and Document License. This is the baseline assumption for charters. But it seems reasonable to be explicit about this. 

The W3C Software and Document License says "permission to copy, modify, and distribute this work, with or without modification, for any purpose and without fee or royalty is hereby granted", with only notice and attribution requirements. Maybe these restrictions are not sufficiently clear. But I'm not sure it is appropriate for the charter to interpret a legal document. A copyright license is a legal document. If anyone is unclear on what a legal document implies, it would be best to consult an attorney. (Apple in-house counsel have reviewed the W3C Software and Document License as well as a draft of the charter.)

Besides this, it's not totally clear to me what you are asking for. The charter should not be ambiguous of course, but I am honestly not sure what is unclear.

**Comment by kenrussell** [comment]
I've consulted Google's in-house counsel.

It seems that the sort of clarifications I was hoping for are beyond the scope of the CG's charter, so I will close this issue.

For the record, I and others remain concerned about whether the open source software deliverables from this CG can truly be *used* for any purpose.
