### ISSUE TITLE
Repo no longer published as GitHub Pages?

### ISSUE THREAD

**Issue by tidoust** [gpuweb/admin#16]
The CG charter seems to be no longer available at https://gpuweb.github.io/admin/cg-charter.html

 @grorg @Kangz, I suspect that publication of the repo as GitHub Pages is no longer active, possibly since the repo was switched to `main`?

**Comment by kainino0x** [comment]
I think I fixed it, will have to check once the site publishes.

**Comment by kainino0x** [comment]
oh, it's done.
