### ISSUE TITLE
TPAC meeting with Immersive Web

### ISSUE THREAD

**Issue by Yonet** [gpuweb/admin#17]
Hi Chairs and editors,
As the Immersive web working group, we think it might be useful for us to meet face to face/online as part of TPAC. We are currently scheduling our meetings for below dates. If you are interested, please let us know if any of the dates below or another time would work for you.

Current time slots for planned meetings: 
7-10pm UTC on Monday 2nd of November,
4-8pm on Tuesday 3rd of November
4-8pm on Wednesday 4th of November
6-10pm on Thursday 5th of November
6-10pm on Friday 5th of November

Thank you!

Immersive-web chairs

**Comment by charlestonxorg** [comment]
No
