### ISSUE TITLE
s/3D on the Web/GPU on the Web/

### ISSUE THREAD

**Issue by Kangz** [gpuweb/admin#4]
The charter mentions "3D on the Web" multiple times, it should be updated to be "GPU on the Web" instead.

**Comment by ghost** [comment]
And a catchy acronym wouldn't hurt.

**Comment by grorg** [comment]
We're happy to offer the "WebGPU" name, even if it ends up being different from our prototype/proposal (which we always expected to be the case).

However, I'm not sure the charter needs to use that name.

I'll fix the 3D on the Web errors.

**Comment by ghost** [comment]
Hi Dean,

Could you please remove me from the group? Here are my credentials:

email: wnyessen@gmail.com <mailto:wnyessen@gmail.com>
name: William Yessen

Thanks a lot!

William

**Comment by grorg** [comment]
@insomniac-scientist - from the W3C group? I think you need to do it. There should be a button on
https://www.w3.org/community/gpu/
