### ISSUE TITLE
Add an ANGLE-like library to the deliverables

### ISSUE THREAD

**Issue by Kangz** [gpuweb/admin#7]
In addition to a test suite, an other extremely valuable software artifact that the CG could produce is a ANGLE-like library implementing the translation of the API to the native APIs. This would allow most of the work to be shared between browser vendors, with only the integration of the library with the JS bindings being specific to each browser. For example in Chromium's prototype only a fraction of the code is backend specific, see [this slide](https://docs.google.com/presentation/d/1mLQEM__twfivV7nJLDBIomS9pegOYkJQWyM6lTse4PQ/edit#slide=id.g1b8fd28e7e_0_145).

Another nice advantage of such a library would be that during development, applications could test in native before getting compiled for the Web, making the development workflow much easier.

**Comment by grorg** [comment]
It seems we agree in #8 to add an optional software deliverable for this.

**Comment by Kangz** [comment]
Yep, closing as fixed.
